### ISSUE TITLE
Petit soucis d'affichage sur grand écran

### ISSUE THREAD

**Issue by hiwelo** [StrasWeb/wordpress-template-strasweb#1]
Il serait peut-être intéressant de mettre le footer en absolute pour éviter ça : 

![capture d ecran 2015-01-03 a 21 54 56](https://cloud.githubusercontent.com/assets/4989733/5603709/5115bd56-9393-11e4-9f04-14b71cce7d8c.png)

**Comment by Rudloff** [comment]
J'ai trouvé une solution en CSS finalement : http://matthewjamestaylor.com/blog/keeping-footers-at-the-bottom-of-the-page
