### ISSUE TITLE
Lien hypertexte déborde en hauteur sur écran xs

### ISSUE THREAD

**Issue by BlackAro** [StrasWeb/wordpress-template-strasweb#4]
Sur mobile, les liens pour « Découvrez nos dernières réalisations » et « Références » débordent en hauteur, dépassant les limites de l'image et masquant le titre.

![strasweb_issue_links](https://cloud.githubusercontent.com/assets/7115219/5819228/7cac04da-a0bc-11e4-92eb-a431ee7c553e.png)

**Comment by Rudloff** [comment]
Merci pour le signalement. J'ai amélioré un peu ça.
