### ISSUE TITLE
Check that we always provide fallback fonts

### ISSUE THREAD

**Issue by Rudloff** [StrasWeb/wordpress-template-strasweb#5]
`font-family` rules should always end with `sans` or `sans-serif`.

**Comment by hiwelo** [comment]
Or cursive, or monospaced, etc. ;)
Le 23 janv. 2015 19:17, "Pierre Rudloff" notifications@github.com a écrit
:

**Comment by Rudloff** [comment]
I'm pretty sure we don't use those types in this template (but I get your point).
